/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VestingRouteImport } from './routes/vesting'
import { Route as LockRouteImport } from './routes/lock'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as ClmmRouteImport } from './routes/clmm'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const VestingRoute = VestingRouteImport.update({
  id: '/vesting',
  path: '/vesting',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const ClmmRoute = ClmmRouteImport.update({
  id: '/clmm',
  path: '/clmm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/clmm': typeof ClmmRoute
  '/farm': typeof FarmRoute
  '/lock': typeof LockRoute
  '/vesting': typeof VestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/clmm': typeof ClmmRoute
  '/farm': typeof FarmRoute
  '/lock': typeof LockRoute
  '/vesting': typeof VestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/clmm': typeof ClmmRoute
  '/farm': typeof FarmRoute
  '/lock': typeof LockRoute
  '/vesting': typeof VestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/clmm' | '/farm' | '/lock' | '/vesting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/clmm' | '/farm' | '/lock' | '/vesting'
  id: '__root__' | '/' | '/dashboard' | '/clmm' | '/farm' | '/lock' | '/vesting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ClmmRoute: typeof ClmmRoute
  FarmRoute: typeof FarmRoute
  LockRoute: typeof LockRoute
  VestingRoute: typeof VestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vesting': {
      id: '/vesting'
      path: '/vesting'
      fullPath: '/vesting'
      preLoaderRoute: typeof VestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clmm': {
      id: '/clmm'
      path: '/clmm'
      fullPath: '/clmm'
      preLoaderRoute: typeof ClmmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ClmmRoute: ClmmRoute,
  FarmRoute: FarmRoute,
  LockRoute: LockRoute,
  VestingRoute: VestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
